---
name: Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@2b5b058e3db41a3328fd9a6a58fd4c2545a14353 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
