---
name: Greetings

on: [pull_request, issues]

permissions:
  contents: read

jobs:
  greeting:
    permissions:
      issues: write  # for actions/first-interaction to comment on first issue
      pull-requests: write  # for actions/first-interaction to comment on first PR
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      if: env.month != 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue! 😊🕹️'
        pr-message: 'Thank you for contributing to this project! 😊🕹️'
    - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
      if: env.month == 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue! Happy Hacktoberfest!!! 🎃👕🕹️'
        pr-message: 'Thank you for contributing to this project. Happy Hacktoberfest!!! 🎃👕🕹️'
